### ISSUE TITLE
Improve add_requires and find_package to integrate the 3rd package manager

### ISSUE THREAD

**Issue by waruqi** [xmake-io/xmake#339]
### Roadmap

- [x] `add_requires("XXX::pkgname")` -> `package.manager.install_package("XXX::pkgname")`
  - [x] conan::zlib/1.2.11@conan/stable
  - [x] vcpkg::zlib
  - [x] brew::pcre2/libpcre2-8
- [x] `lib.detect.find_package("XXX::pkgname")` 
  - [x] conan::zlib/1.2.11@conan/stable
  - [x] vcpkg::zlib
  - [x] brew::pcre2/libpcre2-8
  - [x] pkg_config::zlib
- [x] Add builtin api `find_packages("XXX:pkgname", "zlib")` to find multiple packages
- [x] Custom integration with the other package manager
  

### Conan

- [x] pass platform settings
- [x] pass architecture settings
- [x] pass build mode settings
- [x] pass compiler settings
  - [x] gcc
  - [x] clang
  - [x] msvc
- [x] cross-platform test verification 
  - [x] macOS x86_64
  - [x] linux/ubuntu x86_64
  - [x] windows x86/x86_64 
- [x] install_package("conan::xxx", config = {})
  - [x] settings, e.g. `settings = {"compiler=gcc", "compiler.version=4.9"}`
  - [x] build_requires, e.g. `build_requires = "xmake_generator/0.1.0@bincrafters/testing"`
  - [x] build, e.g. `build = "all"`
  - [x] options, e.g. `options = {"OpenSSL:shared=True"}`
  - [x] imports
  - [x] remote, e.g. `remote = "https://api.bintray.com/conan/bincrafters/public-conan"`
 
* [conan-xmake_generator](https://github.com/tboox/conan-xmake_generator)
* [conan-xmake_installer](https://github.com/bincrafters/conan-xmake_installer)
* https://github.com/tboox/xmake/tree/dev/xmake/modules/package/manager/conan

### Related issues

#327 Integrate with Conan package manager
#184 Improve lib.detect.find_package to support vcpkg
#69 Remote package management
#331 Creating xmake_generator for Conan
#330 Creating xmake_installer conan package
#332 Creating xmake "Build Helper" for Conan

**Comment by waruqi** [comment]
### Examples

```lua
add_requires("CONAN::zlib/1.2.11@conan/stable", {alias = "zlib", debug = true, config = {build_requires = "xmake_generator/0.1.0@bincrafters/testing", build = "all"}})
add_requires("CONAN::OpenSSL/1.0.2n@conan/stable", {alias = "openssl", config = {build_requires = "xmake_generator/0.1.0@bincrafters/testing",
                                                                                 options = "OpenSSL:shared=True",
                                                                                 build = "all"}})

target("test")
    set_kind("binary")
    add_files("src/*.c") 
    add_packages("openssl", "zlib")
```

**Comment by waruqi** [comment]
```lua

```lua
add_requires("CONAN::zlib/1.2.11@conan/stable", {alias = "zlib", debug = true, 
    config = {build_requires = "xmake_generator/0.1.0@bincrafters/testing", build = "all"}})

add_requires("CONAN::OpenSSL/1.0.2n@conan/stable", {alias = "openssl", 
    config = {build_requires = "xmake_generator/0.1.0@bincrafters/testing",
    options = "OpenSSL:shared=True", build = "all"}})

target("test")
    set_kind("binary")
    add_files("src/*.c") 

    on_load(function (target)
        target:add(find_packages("CONAN::OpenSSL/1.0.2n@conan/stable"))
        target:add(find_packages("CONAN::zlib/1.2.11@conan/stable", {mode = "debug"}))
    end)
```

**Comment by waruqi** [comment]
### Related issues

#327 
#184 
#69 
#331

**Comment by waruqi** [comment]
User can also add the custom module to integrate with the 3rd package manager in projectdir/xmake.lua.

We do not need to modify the xmake project source code.

- projectdir
  - main.c
  - xmake.lua
  - modules
    - package/manager/xxx
      - install_package.lua
      - find_package.lua

```lua
add_moduledirs("modules")
add_requires("xxx::zlib", {alias = "zlib"})
target("test")
    add_files("*.c")
    add_packages("zlib")
```

**Comment by waruqi** [comment]
### Example

Install and use brew packages

```lua
add_requires("brew::zlib", {alias = "zlib"}})
add_requires("brew::pcre2/libpcre2-8", {alias = "pcre2"}})

target("test")
    set_kind("binary")
    add_files("src/*.c") 
    add_packages("pcre2", "zlib")
```

**Comment by waruqi** [comment]
Add clib support https://github.com/xmake-io/xmake/issues/397
